version: '3'

services:
  ifcb_annotate:
    build: .
    container_name: ifcb_annotate
    volumes:
      - ./python/env/manualclassify:/code
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 80:8000
    networks:
      - postgresql_network
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - postgresql_network
    volumes:
      - annotate_db:/var/lib/postgresql/data
      - ./backups:/backups

networks:
  postgresql_network:
    driver: bridge

volumes:
  annotate_db:
